CREATE TABLE users (
    id uuid PRIMARY KEY,
    email text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    role text NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    preferences jsonb NOT NULL DEFAULT '[]',
    profile_version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE items (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000) PRIMARY KEY,
    title text NOT NULL CHECK (length(title) BETWEEN 1 AND 300),
    genres jsonb NOT NULL,
    active boolean NOT NULL DEFAULT true
);
CREATE TABLE models (
    version text PRIMARY KEY,
    manifest_sha256 text NOT NULL,
    evaluation jsonb NOT NULL,
    registered_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE catalog_settings (
    singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
    catalog_version bigint NOT NULL DEFAULT 1,
    active_model text NOT NULL REFERENCES models(version)
);
CREATE TABLE events (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id),
    item_id integer NOT NULL REFERENCES items(id),
    kind text NOT NULL CHECK (kind IN ('view', 'like', 'dislike', 'rating_import')),
    occurred_at timestamptz NOT NULL,
    request_id text NOT NULL,
    request_hash text NOT NULL,
    applied boolean NOT NULL,
    result_profile_version bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(user_id, request_id)
);
CREATE INDEX events_user_page ON events(user_id, id);
CREATE TABLE user_item_state (
    user_id uuid NOT NULL REFERENCES users(id),
    item_id integer NOT NULL REFERENCES items(id),
    weight double precision NOT NULL CHECK (weight >= 0 AND weight <= 3),
    occurred_at timestamptz NOT NULL,
    event_id bigint NOT NULL REFERENCES events(id),
    PRIMARY KEY(user_id, item_id)
);
